spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employees?createDatabaseIfNotExist=true
    password: 1123Mind@Blown
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update