package tryapp.dao;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import tryapp.domain.User;
import tryapp.repositories.UserRepository;

import java.util.List;
import java.util.Optional;

@Component
public class UserDaoImpl implements UserDao{

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@Override
	public List<User> getUsers() {
		return (List<User>) userRepository.findAll();
	}

	@Override
	public User createUser(User user) {
		return userRepository.save(user);
	}

	@Override
	public Optional<User> findById(int id) {
		return userRepository.findById(id);
	}

}
